info:
  stage: dev
  version: '@project.version@'
server:
  port: '@server.port@'
management:
  server:
    port: '@management.port@'
  metrics:
    export:
      prometheus:
        enabled: false
    tags:
      application: messages
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
messages:
  db:
    batch-size: 1000
spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
    password: '@db.password@'
    url: '@db.url@'
    username: '@db.user@'
  flyway:
    enabled: true
    password: '@db.password@'
    url: '@db.url@'
    user: '@db.user@'
